language: c  
sudo: false # only for faster builds  
script:  
 - gcc -o test test.c  
 - ./test  

 language: python
 python:  
  - "3.6"  
cache: pip  
# command to install dependencies    
before_script:  
  - easy_install distribute   
# command to run tests    
script:   
  - python Minesweeper.py  
