language: python3
 python:  
  - "3.5"  
cache: pip  
# command to install dependencies    
before_script:  
  - easy_install distribute   
# command to run tests    
script:   
  - python Minesweep.py  
